# NumPy Basics

In [1]:
import numpy as np

## Efficiency

In [2]:
%timeit -n 1000 [x**2 for x in range(1000)]
%timeit -n 1000 np.arange(1000) ** 2

326 µs ± 18.1 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)
2.78 µs ± 292 ns per loop (mean ± std. dev. of 7 runs, 1000 loops each)


## Creating a Simple Array

In [3]:
ar = [1, 2, 3, 4, 5]
np.array(ar)

array([1, 2, 3, 4, 5])

### Getting Basic Information about an Array

In [4]:
ar = np.array([1,2,3,4,5])

print(f'''Object type: {type(ar)}
Array size: {np.size(ar)},
Array dimensions: {ar.ndim},
Array data type: {ar.dtype}''')

Object type: <class 'numpy.ndarray'>
Array size: 5,
Array dimensions: 1,
Array data type: int32


### np.arange()

In [5]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [6]:
np.arange(5, 11)

array([ 5,  6,  7,  8,  9, 10])

In [7]:
np.arange(0, 13, 3)

array([ 0,  3,  6,  9, 12])

In [8]:
np.arange(4, -4, -1)

array([ 4,  3,  2,  1,  0, -1, -2, -3])

In [9]:
np.arange(1, 5, .5)

array([1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5])

In [10]:
ar5 = np.arange(1, 5, 1)
ar6 = np.arange(1, 5, .5)
ar7 = np.arange(1, 5, dtype=float)

type(ar5[0]), type(ar6[0]), type(ar7[0])

(numpy.int32, numpy.float64, numpy.float64)

In [11]:
ar = np.arange(1, 10)
ar[5] = 1.5

type(ar[0]), type(ar[5]), ar

(numpy.int32, numpy.int32, array([1, 2, 3, 4, 5, 1, 7, 8, 9]))

## Similar to Lists
ndarrays are iterators

In [12]:
my_list = [x**2 for x in range(10)]
for i in my_list:
    print(i, end=' ')

print('\n' + '='*25) # Separator

my_array = np.arange(10) ** 2
for i in my_array:
    print(i, end=' ')

0 1 4 9 16 25 36 49 64 81 
0 1 4 9 16 25 36 49 64 81 

## Different from Lists

### Operators that behave differently

In [13]:
my_list = [1, 2, 3, 4, 5]
print(my_list)
print(my_list + my_list) # Appends list to itself.
print(my_list * 3) # Repeats list three times.

[1, 2, 3, 4, 5]
[1, 2, 3, 4, 5, 1, 2, 3, 4, 5]
[1, 2, 3, 4, 5, 1, 2, 3, 4, 5, 1, 2, 3, 4, 5]


In [14]:
ar = np.arange(1, 6)
print(ar)
print(ar + ar) # Adds ar[0] to ar[0], ar[1] to ar[1], etc.
print(ar * 3) # Multiplies each element of array by 3.

[1 2 3 4 5]
[ 2  4  6  8 10]
[ 3  6  9 12 15]


In [15]:
ar1 = np.arange(1, 6)
multiplier = 2
my_list = [2, 2, 2, 2, 2]
ar2 = np.array(my_list)

result1 = ar1 * multiplier
result2 = ar1 * my_list
result3 = ar1 * ar2

result1, result2, result3

(array([ 2,  4,  6,  8, 10]),
 array([ 2,  4,  6,  8, 10]),
 array([ 2,  4,  6,  8, 10]))

In [16]:
ar = np.arange(1, 6)

In [17]:
ar + 2 # Add 2 to each element of array.

array([3, 4, 5, 6, 7])

In [18]:
ar - 2 # Subtract 2 from each element of array.

array([-1,  0,  1,  2,  3])

In [19]:
ar / 2 # Divide each element of array by 2.

array([0.5, 1. , 1.5, 2. , 2.5])

In [20]:
ar ** 2 # Square each element of array.

array([ 1,  4,  9, 16, 25], dtype=int32)

In [21]:
ar ** .5 # Get square root of each element of array.

array([1.        , 1.41421356, 1.73205081, 2.        , 2.23606798])

In [22]:
ar += 10 # Add 10 to each element of array

## Universal Functions

### Zipping two iterables

In [23]:
r1 = range(1, 10)
r2 = range(10, 1, -1)
zip(r1, r2)

### Displaying the zip as a list

In [24]:
list(zip(r1, r2))

[(1, 10), (2, 9), (3, 8), (4, 7), (5, 6), (6, 5), (7, 4), (8, 3), (9, 2)]

### Creating a list of multiples from the zip

In [25]:
[i1 * i2 for i1, i2 in zip(r1, r2)]

[10, 18, 24, 28, 30, 30, 28, 24, 18]

### Multiplying two ndarrays

In [26]:
ar1 = np.arange(1, 10)
ar2 = np.arange(10, 1, -1)
np.multiply(ar1, ar2)

array([10, 18, 24, 28, 30, 30, 28, 24, 18])

### Adding array-like objects

In [27]:
my_list = [1, 3, 5, 7]
r = range(0, 4)
np.add(my_list, r)

array([ 1,  4,  7, 10])

### Some Examples of Universal Functions

In [28]:
ar_ints = np.arange(1, 6)
ar_floats = np.arange(1, 7.5, 1.5)
ar_ints, ar_floats

(array([1, 2, 3, 4, 5]), array([1. , 2.5, 4. , 5.5, 7. ]))

In [29]:
np.add(ar_ints, ar_floats)

array([ 2. ,  4.5,  7. ,  9.5, 12. ])

In [30]:
np.negative(ar_ints)

array([-1, -2, -3, -4, -5])

In [31]:
np.square(ar_ints)

array([ 1,  4,  9, 16, 25], dtype=int32)

In [32]:
np.hypot(ar_ints, ar_ints)

array([1.41421356, 2.82842712, 4.24264069, 5.65685425, 7.07106781])

In [33]:
np.greater(ar_ints, ar_floats)

array([False, False, False, False, False])

In [34]:
np.ceil(ar_floats)

array([1., 3., 4., 6., 7.])