In [1]:
import numpy as np

### Create Generator

In [2]:
rng = np.random.default_rng()

### Generate random floats
Run the sell repeatedly and notice that it generates different numbers every time.

In [3]:
rng.random()

0.676944328780018

In [4]:
rng.random(5)

array([0.31856541, 0.18497459, 0.47165472, 0.33485853, 0.70564814])

### Random Integers

In [5]:
rng.integers(0, 100)

52

In [6]:
rng.integers(0, 100, 5)

array([16,  8, 30, 73, 35], dtype=int64)

### Random Choices

In [7]:
ar = np.array(['rock', 'paper', 'scissors'])
rng.choice(ar)

'paper'

In [8]:
rng.choice(ar, 4)

array(['rock', 'scissors', 'scissors', 'paper'], dtype='<U8')

In [9]:
rng.choice(ar, 3, replace=False)

array(['paper', 'scissors', 'rock'], dtype='<U8')

### The `size` Parameter

In [10]:
rng.random((3, 5))

array([[0.39920694, 0.82772217, 0.86126097, 0.99060845, 0.76659404],
       [0.31749942, 0.19150489, 0.41857884, 0.5186278 , 0.2165201 ],
       [0.67584537, 0.810856  , 0.0921513 , 0.07126138, 0.08860698]])

In [11]:
rng.integers(1, 100, (3, 5))

array([[ 9, 26, 26, 67, 41],
       [74, 56, 59, 79, 81],
       [32, 25, 37, 34, 38]], dtype=int64)

In [12]:
rng.choice(['rock', 'paper', 'scissors'], (5, 2))

array([['paper', 'paper'],
       ['scissors', 'rock'],
       ['paper', 'scissors'],
       ['rock', 'scissors'],
       ['rock', 'rock']], dtype='<U8')

### Use `seed` to regenerate the same random numbers.
Run the sell multiple times and notice it generates the same numbers every time.

In [13]:
rng = np.random.default_rng(seed=42)
rng.random(), rng.integers(1, 100), rng.choice(['rock', 'paper', 'scissors'])

(0.7739560485559633, 65, 'paper')

## Create a 5-card Poker Hand
(Just for fun)

In [14]:
def get_deck():
    suits = ['Clubs', 'Diamonds', 'Hearts', 'Spades']
    values = list(range(2, 11)) + list('JQKA')
    deck = [(s, v) for s in suits
                   for v in values]
    return deck

seed = 112631
rng = np.random.default_rng(seed=seed)

deck = get_deck()
ar = np.array(deck)

poker_hand = rng.choice(ar, 5, replace=False)
poker_hand

array([['Clubs', 'Q'],
       ['Clubs', 'K'],
       ['Clubs', 'J'],
       ['Clubs', '10'],
       ['Clubs', 'A']], dtype='<U8')