# Using Boolean Arrays

In [1]:
import numpy as np

In [2]:
np.random.seed(1)
ar = np.random.randint(100, size=10)
ar

array([37, 12, 72,  9, 75,  5, 79, 64, 16,  1])

In [3]:
ar_isodd = ar % 2 == 1
ar_isodd

array([ True, False, False,  True,  True,  True,  True, False, False,
        True])

In [4]:
ar[ar_isodd]

array([37,  9, 75,  5, 79,  1])

In [5]:
ar[ar % 2 == 1]

array([37,  9, 75,  5, 79,  1])